### ISSUE TITLE
Blocks/items look wrong

### ISSUE THREAD

**Issue by LaycockBen** [PolymerPorts/cc-tweaked-patch#2]
![ComputerCraft](https://github.com/PolymerPorts/cc-tweaked-patch/assets/10056435/6c76293b-8498-4bc4-8915-a90599fe7417)

Patch currently seems to break computercraft block appearance, texture references wrong itemids? (nether brick for computer icon, ghast tear 'block' for world block).  UI seems to load keyboard/mouse/screen when using it correctly.

**Comment by Patbox** [comment]
You need to setup a server resource pack for it to work. See this guide https://polymer.pb4.eu/latest/user/resource-pack-hosting/

**Comment by LaycockBen** [comment]
Thanks for that, I'd completely misunderstood what polymer was doing!
